name: Run Appium Test on BrowserStack

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-browserstack-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v3

    - name: 🧳 Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: ☕ Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 🧪 Run Appium Test on BrowserStack
      working-directory: ./TestAppiumDemo
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      run: |
        echo "✅ Running tests with:"
        echo "BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME"
        echo "BROWSERSTACK_ACCESS_KEY=${BROWSERSTACK_ACCESS_KEY:0:4}********"

        mvn -Dtest=browserstack.androidTestFlow \
            -DBROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME \
            -DBROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY test
