name: Build and Cache Android Emulator AVD (One-time)

on:
  workflow_dispatch:

jobs:
  build-avd:
    runs-on: macos-13
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android Command Line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -O https://dl.google.com/android/repository/commandlinetools-mac-9477386_latest.zip
          unzip -q commandlinetools-mac-*.zip
          mv cmdline-tools latest
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/emulator" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Install SDK and Create Emulator (Android 30)
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "emulator" "system-images;android-30;google_apis;x86"
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" --device "pixel"

      - name: Archive AVD for Cache
        run: |
          mkdir -p avd-backup
          cp -r ~/.android/avd avd-backup/
          cp ~/.android/*.ini avd-backup/ || true

      - name: Upload AVD Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-avd
          path: avd-backup
